CREATE TABLE DBNUTRIAGENDA.TB_USUARIO(
   ID              INTEGER UNIQUE NOT NULL,
   DS_NOME         TEXT    NOT NULL,
   DS_SOBRENOME    INT     NOT NULL,
   DS_EMAIL        CHAR(50),
   DS_TOKEN        REAL,
   PRIMARY KEY(ID)
);